### PR TITLE
Feature/load csv to graph

### PR DESCRIPTION
**Pull request by Alessandro100**
This PR allows a user to load a .csv and have it display in a graph. The format of the .csv it accepts is as such

{{column 1}} | {{column 2}}
      0                       2
      3                       4

Screen Shot 2020-10-22 at 3 51 22 PM

For the future:
- I would have liked to write tests for this component but I was wasting a lot of time trying to configure tests on Qt as it's not very straight forward. This is something to consider in the future but as there is still a lot to do, I figured it would be better to push forward

### CODE REVIEW

**Review by alexbara2000 — APPROVED** [review]
looks good!

**Comment by johnstonstott** [comment]
@Alessandro100 So I'd like to run it to make sure but I've never worked with this before lol. Which IDE are you using? I'll set it up and play around with it a bit on my end over the weekend.

**Comment by Alessandro100** [comment]
Hey @johnstonstott we are using Qt! If you download it, it comes with the Qt Creator IDE. I added information in the README on how to run it (warning: it's like 20 gigs). Let me know if you have any issues running it!

**Review by johnstonstott — CHANGES_REQUESTED** [review]
Looks really good! 

I have no problems reading a demo CSV, I tried with 0, negative numbers, floats etc. and all worked great like below: 
image

However, when there is an empty Y value, I notice some weird behaviour. It changes the title of the X axis to the corresponding X with no value. See below for the values I used and output I got, you can compare to the first screenshot to see that the Y axis title disappears and the X axis title changes to 10.
image

This might not seem like an important issue but I believe Alex discovered that when there is no data, Motec leaves the cell empty (instead of adding a 0 or something like that). @alexbara2000 can you confirm? So I think this is something we should handle.

It looks like we might be able to fix this by changing the way the `LoadCsvFile()` function works. Let me know if you need any help with this! Besides that, looks really awesome!

**Comment by Alessandro100** [comment]
ok awesome, I'll look into this!

**Comment by Alessandro100** [comment]
@johnstonstott I fixed the bug, let me know if its good to go

**Review by johnstonstott — APPROVED** [review]
Looks great! I think replacing empty values with 0 makes the most sense. Everything still runs well, nice job.

**Pull request merged**
