### PR TITLE
Feature/dynamic graphs

### PR DESCRIPTION
**Pull request by Alessandro100**
Whats been done
- Ability to add live data graphs dynamically
- Ability to add csv data graphs dynamically
- Ability to remove live data graphs dynamically
- Ability to remove csv data graphs dynamically

Things to note
- I added the 'chose an attribute' box on the live data graph but it doesn't do anything besides set a property. This is due to not knowing the structure of the data coming from the server
- I made the UI based on simplicity but is subject to change

image

### CODE REVIEW

**Comment by rickyelopez** [comment]
you should squash your commits, want me to show you how?

Also, PRs should always be linked to a related issue. If an issues doesn't already exist for this, can you create one?

**Comment by Alessandro100** [comment]
I can squash the commits! This PR is linked to an issue! (#11). Do you have the Zenhub chrome extension installed? Thats what we use to manage tickets (It's like Trello but built into Github). Other than the squash, is the code good to go?

**Review by johnstonstott — APPROVED** [review]
Looks great! 🥇 Works very well for adding new graphs and seeing live/static graphs at the same time. Excellent work!

Something I noticed while testing is that the server has to be running before opening the program. If you run the program and start the server afterwards it doesn't connect. My guess is that the logic to connect to the server runs when the window first opens up? Maybe we can move this logic so that it tries to connect when adding a new live graph instead? This is very minor but still something I think we should keep in mind.

**Comment by Alessandro100** [comment]
Yeah we will have to better handle the way we connect to the server, I think we have a story which says 'connect to the server on the click of a button'

**Pull request merged**
